# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
 
    #Virtual Machine settings
  
    config.vm.box = "ubuntu/bionic64"
    config.vm.hostname = "master-node"
  
    #Provider settings
  
    config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.name = "k8s-master"
      vb.cpus = 2
    end
  
    #Network Settings
    
     #config.vm.network "forwarded_port", guest: 80, host: 8080
    # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
    config.vm.network "private_network", ip: "192.168.56.69"
    # config.vm.network "public_network"

end